### ISSUE TITLE
Support truffleruby 2.20.3

### ISSUE THREAD

**Issue by HoneyryderChuck** [flavorjones/docker-truffleruby#3]
Coming from https://github.com/oracle/truffleruby/issues/1449#issuecomment-753972997

Current latest image is bundling truffleruby 2.20.2 . 2.20.3 has already shipped.

**Comment by flavorjones** [comment]
I wasn't aware 20.3 had shipped, updating dockerfiles now.

**Comment by flavorjones** [comment]
Dockerhub is building the 20.3 images now.

**Comment by HoneyryderChuck** [comment]
thx for the quick action!

Do you know how these version updates can become more visibly noticed in the future? Don't know what's the ruby (or jruby) docker image release policy, or whether it's the same team handling both the official and docker images releases.

**Comment by eregon** [comment]
It'd be nice to have the Docker images available soon after the release.
I do a few steps after a release, notably https://github.com/oracle/truffleruby/blob/master/doc/contributor/updating-ruby-installers.md
Maybe I could do a PR here when there is a new release, if it's just running some script like `update-dockerfiles`?

Are the Docker images built as soon as a commit is merged to `master`?

FWIW, there is also a list of dates for future releases at https://www.graalvm.org/release-notes/version-roadmap/

**Comment by flavorjones** [comment]
@eregon I'm subscribed to the TR releases now so I'm happy to take the action to bump the docker image version.

Alternatively, if you want to make it an action item to send a PR here, it's pretty easy to update these images:

1. update the variable `TRUFFLERUBY_STABLE_VERSION` at the top of https://github.com/flavorjones/docker-truffleruby/blob/master/update-dockerfiles
2. run `./update-dockerfiles`
3. update the README with up-to-date tag names (which could also be scripted, I've just been too lazy to do so yet)

And I believe the image builder will get kicked off as soon as the change hits master.

**Comment by eregon** [comment]
> @eregon I'm subscribed to the TR releases now so I'm happy to take the action to bump the docker image version.

Great!
I'm happy if you do it, as I already have quite a few things to do after a release :)
