### ISSUE TITLE
Missing 21.0.0 tags on DockerHub

### ISSUE THREAD

**Issue by petenorth** [flavorjones/docker-truffleruby#4]
Thank you for maintaining these images - I'm now using them on my hobby project.

I can't seem to find the 21.0.0 tags though?

**Comment by flavorjones** [comment]
:thinking: Weird, ok, let me look into what's going on.

**Comment by flavorjones** [comment]
Ah - I forgot to push the git tag `stable-21.0.0` and so the dockerhub builds didn't kick off.

I just pushed the tag, so give the dockerhub build infrastructure an hour or so to generate all the tagged images. I'll leave this open until I confirm they're built.

Thanks for your patience!

**Comment by flavorjones** [comment]
The images are built and available on dockerhub! Thanks again.
