### ISSUE TITLE
Docker images for 21.1.0

### ISSUE THREAD

**Issue by eregon** [flavorjones/docker-truffleruby#5]
Hello,

I noticed that 21.1.0 is not currently available on Docker Hub: https://hub.docker.com/r/flavorjones/truffleruby/tags?page=1&ordering=last_updated
That part is probably not yet automated I guess.
Could you trigger it when you get some time?

**Comment by eregon** [comment]
Something else I noticed on that link is that `stable`, `buster-slim` and `buster` all seem daily updated, while `21.0.0` and `21.0.0-buster` are not (as expected).
Is that because the first 3 automatically pick the latest release maybe?

**Comment by flavorjones** [comment]
Hi, as mentioned in other issues, the Dockerfiles in this repo need to be manually updated today. I'm open to automating this somehow, but haven't made the time to do so.

I've just pushed ced0954 which will kick off builds of 21.1.0.

**Comment by flavorjones** [comment]
The versioned builds are triggered only by a git tag on the repository. All the other builds are triggered on any `git push` or by the webhook. This is less than optimal, but I'm not entirely sure if it's avoidable because of how challenging it is to get dockerhub to build these images.

I'm considering using Github Actions to build the images instead, and then pushing to both a Github Package Registry and DockerHub.

**Comment by eregon** [comment]
Thank you. I think it's fine to keep this bit manual since it's only one release every 3 months.
If the only needed action is to push a commit like https://github.com/flavorjones/docker-truffleruby/commit/ced09542a15566d329153aab4147ec16b7e2f2e6 I could make a PR or even push it directly, as you prefer.
I already have a list of things to do on release (https://github.com/oracle/truffleruby/blob/master/doc/contributor/updating-ruby-installers.md), so I'd just add this step.

**Comment by flavorjones** [comment]
@eregon I've added https://github.com/flavorjones/docker-truffleruby/blob/master/CONTRIBUTING.md which should be complete instructions for what to do. If you want to send a PR next time, that would be much appreciated. If I move to Github Actions and add you as a collaborator (or transfer the project to you?) that might be a complete solution.

**Comment by eregon** [comment]
Thank you, I'll make a PR next time then.

**Comment by flavorjones** [comment]
DockerHub build queue is moving slowly, I'll try to keep an eye out and update this issue when the images are ready.

More evidence that I should invest in migrating to Github Actions.

**Comment by flavorjones** [comment]
21.1.0 images were published earlier today.
